# Generated by Django 4.2.4 on 2024-05-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_auto_20240511_1507"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productitem",
            name="quantity",
        ),
        migrations.AddField(
            model_name="productitem",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="color",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="size",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
