# Generated by Django 4.2.4 on 2024-05-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_productitem_quantity_productitem_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="color",
            name="slug",
            field=models.SlugField(),
        ),
    ]
