# Generated by Django 4.2.4 on 2024-05-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_color_name_alter_color_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="color",
            options={
                "ordering": ("name",),
                "verbose_name": "color",
                "verbose_name_plural": "colors",
            },
        ),
        migrations.AlterModelOptions(
            name="size",
            options={
                "ordering": ("name",),
                "verbose_name": "size",
                "verbose_name_plural": "sizes",
            },
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="core_produc_id_799af9_idx",
            old_fields=("id", "slug"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="core_produc_name_be3252_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created"], name="core_produc_created_03f4e6_idx"
            ),
        ),
    ]
