# Generated by Django 4.2.4 on 2024-05-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_color_options_alter_size_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("M", "Men"), ("W", "Women"), ("B", "Both")],
                default="B",
                max_length=10,
            ),
        ),
    ]
