# Generated by Django 4.2.4 on 2024-05-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_product_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("M", "men"), ("W", "women"), ("B", "both")],
                default="B",
                max_length=10,
            ),
        ),
    ]
