# Generated by Django 4.2.4 on 2024-05-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_product_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("men", "Men"), ("women", "Women"), ("both", "Both")],
                default="both",
                max_length=10,
            ),
        ),
    ]
