# Generated by Django 4.2.4 on 2024-05-25 21:06

from django.db import migrations


def load_initial_data(apps, schema_editor):
    Category = apps.get_model("core", "Category")
    Size = apps.get_model("core", "Size")
    Color = apps.get_model("core", "Color")

    categories = ["Casual", "Dress", "Sports"]
    sizes = [
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "13.5",
        "14",
    ]
    colors = [
        "Black",
        "Blue",
        "Brown",
        "Cream",
        "Green",
        "Grey",
        "Orange",
        "Red",
        "White",
    ]

    for category in categories:
        Category.objects.create(name=category)

    for size in sizes:
        Size.objects.create(name=size)

    for color in colors:
        Color.objects.create(name=color)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_product_gender"),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
