# Generated by Django 4.2.4 on 2024-05-25 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.SmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
